# The cheatsheet behind F1 in tmux. Printed rather than stored as a text file
# so the layout is one printf format string instead of hand-aligned columns,
# and piped through less so it scrolls and closes on q.
#
# Colours are the terminal's own ANSI slots, which alacritty renders in Nord
# (see alacritty.nix), so this matches the rest of the session without having
# to thread theme.nix through a shell script.

esc=$(printf '\033')
b="${esc}[1m"        # bold, for section headers
k="${esc}[33m"       # yellow, for the keys themselves
d="${esc}[2m"        # dim, for asides
r="${esc}[0m"

head() { printf '\n%s%s%s\n' "$b" "$1" "$r"; }
row() { printf '  %s%-16s%s %s\n' "$k" "$1" "$r" "$2"; }
note() { printf '  %s%s%s\n' "$d" "$1" "$r"; }

help() {
  printf '%s tmux cheatsheet %s   %sprefix is C-a -- "C-a c" means Ctrl+a, release, then c%s\n' \
    "${esc}[7m" "$r" "$d" "$r"

  head 'Sessions'
  row 'C-a d' 'detach (the session keeps running)'
  row 'C-a s' 'pick a session from a list'
  row 'C-a $' 'rename this session'
  note 'tmux ls / tmux attach -t <name> from outside'

  head 'Windows (tabs)'
  row 'C-a c' 'new window, in the current directory'
  row 'C-a 1..9' 'go to window by number'
  row 'C-a C-n / C-p' 'next / previous window'
  row 'C-a ,' 'rename this window'
  row 'C-a w' 'pick a window from a list'
  row 'C-a &' 'kill this window'
  note 'windows renumber themselves when one is closed'

  head 'Panes (splits)'
  row 'C-a |' 'split left/right, in the current directory'
  row 'C-a -' 'split top/bottom, in the current directory'
  row 'C-h C-j C-k C-l' 'move between panes AND vim splits -- no prefix'
  row 'C-a H J K L' 'resize by 5, hold to repeat'
  row 'C-a z' 'zoom this pane to full screen, again to restore'
  row 'C-a space' 'cycle the layouts'
  row 'C-a x' 'kill this pane'
  row 'C-a q' 'show pane numbers, press one to jump'

  head 'Copy mode (vi keys)'
  row 'C-a [' 'enter copy mode; q leaves it'
  row 'v' 'start the selection'
  row 'C-v' 'toggle rectangle/block selection'
  row 'y' 'copy the selection and leave'
  row '/ and ?' 'search forwards / backwards'
  note 'the mouse works too: drag to select, wheel to scroll'
  note 'a copy here lands in the Wayland clipboard, over SSH as well'

  head 'This config'
  row 'F1' 'this cheatsheet'
  row 'C-a R' 'reload ~/.config/tmux/tmux.conf'
  row 'C-a ?' 'every binding, generated by tmux itself'
  note 'the session block in the status bar turns amber while the prefix is armed'
  printf '\n'
}

help | less -R
